spring.application.name=practica01
server.port=8081

spring.datasource.url=jdbc:oracle:thin:@//10.10.0.122:1521/prd
spring.datasource.username=LJBS2024
spring.datasource.password=LJBS2024
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver